### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [teritorio/teritorio-tourism-gl-style#1]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

Would be nice to do this for all the currently maintained styles (and data overlay layers) which are provided.

cc: @frodrigo

**Comment by frodrigo** [comment]
@danieldegroot2 thus gl-style project are only styling of preprocessed OSM data with OpenMapTiles schema. It is rather to project like OpenMapTiles or PlanetTiler to report to Tagsinfo.

- https://github.com/openmaptiles/openmaptiles
- https://github.com/openmaptiles/planetiler-openmaptiles

**Comment by danieldegroot2** [comment]
If Territorio provides overlay OpenStreetMap data or icons on top, do custom routing, show/search/edit other information based on OpenStreetMap data it can be added to Taginfo Projects.

Here are issues for the default map styles
* https://github.com/openmaptiles/openmaptiles/issues/1269
* https://github.com/openmaptiles/planetiler-openmaptiles/issues/125
